package main.java.LiteratureRecommendationSystem.repository;

import main.java.LiteratureRecommendationSystem.domain.Literature;
import main.java.LiteratureRecommendationSystem.domain.Book;
import main.java.LiteratureRecommendationSystem.domain.Manga;
import main.java.LiteratureRecommendationSystem.domain.Encyclopedia;

public class LiteratureRepository extends InMemoryRepository<Literature> {
    public LiteratureRepository() {
        //===Book===
        add(new Book("Rozprávka", 6, "Malý princ", "filozofická rozprávka o priateľstve, láske a zodpovednosti rozprávaná cez cestu malého princa", 1943, "https://www.gutenberg.org/ebooks/1798", "Antoine de Saint-Exupéry", 96));
        add(new Book("Rozprávka", 6, "Alica v krajine zázrakov", "príbeh dievčatka, ktoré spadne do králičej nory a objaví fantastický svet plný zázrakov", 1865, "https://www.gutenberg.org/ebooks/11", "Lewis Carroll", 96));
        add(new Book("Rozprávka", 6, "Charlie a továreň na čokoládu", "príbeh chudobného chlapca, ktorý vyhrá prehliadku tajomnej čokoládovne Willyho Wonku", 1964, "https://archive.org/download/charliechocolat00dahl/charliechocolat00dahl.pdf", "Roald Dahl", 192));
        add(new Book("Rozprávka", 6, "Hobit", "fantasy dobrodružstvo hobita Bilba Pytlíka na ceste za pokladom chráneným drakom Smaugom", 1937, "https://archive.org/download/thehobbit00tolk_0/thehobbit00tolk_0.pdf", "J.R.R. Tolkien", 310));
        add(new Book("Rozprávka", 6, "Pinocchio", "príbeh drevenej bábiky, ktorá sníva o tom stať sa skutočným chlapcom a učí sa rozlišovať dobro od zla", 1883, "https://www.gutenberg.org/ebooks/500", "Carlo Collodi", 280));
        add(new Book("Rozprávka", 8, "Harry Potter a Kameň mudrcov", "príbeh sirotka, ktorý zistí, že je čarodejník a nastúpi do školy čarodejníckej mágie", 1997, "https://books.google.com/books?id=ZDgQCwAAQBAJ", "J.K. Rowling", 320));
        add(new Book("Rozprávka", 8, "Príbeh o dvoch mestách", "historický román o láske a obeti počas francúzskej revolúcie v Londýne a Paríži", 1859, "https://www.gutenberg.org/ebooks/98", "Charles Dickens", 489));
        add(new Book("Rozprávka", 8, "Tajomný ostrov", "dobrodružný príbeh o prežití skupiny ľudí na opustenom ostrove plnom záhad", 1874, "https://www.gutenberg.org/ebooks/1268", "Jules Verne", 512));
        add(new Book("Rozprávka", 8, "Čarodejník z krajiny Oz", "príbeh dievčatka Dorotky, ktorú zanesie víchrnica do kúzelnej krajiny a hľadá cestu domov", 1900, "https://www.gutenberg.org/ebooks/55", "L. Frank Baum", 272));
        add(new Book("Rozprávka", 8, "Spiacej krásky", "príbeh princeznej, ktorú prekliala zlá víla a môže prebudiť len pravý bozk lásky", 1697, "https://www.gutenberg.org/ebooks/10662", "Charles Perrault", 64));
        add(new Book("Román", 10, "Pýcha a predsudok", "román o láske a spoločenských predsudkoch v anglickom vidieckom prostredí 19. storočia", 1813, "https://www.gutenberg.org/ebooks/1342", "Jane Austenová", 432));
        add(new Book("Román", 10, "Anna Kareninová", "tragický príbeh o láske, nevere a spoločenských konvenciách v carskom Rusku", 1877, "https://www.gutenberg.org/ebooks/1399", "Lev Nikolajevič Tolstoj", 864));
        add(new Book("Román", 10, "Veľký Gatsby", "príbeh o americkom sne, láske a bohatstve v období jazzovej éry", 1925, "https://www.gutenberg.org/ebooks/64317", "F. Scott Fitzgerald", 218));
        add(new Book("Román", 10, "Sto rokov samoty", "magický realizmus o rodine Buendía cez sedem generácií v meste Macondo", 1967, "https://books.google.com/books?id=pgPWOaOctq8C", "Gabriel García Márquez", 417));
        add(new Book("Román", 10, "Jane Eyreová", "príbeh osirelej guvernantky, ktorá hľadá lásku a nezávislosť napriek spoločenským prekážkam", 1847, "https://www.gutenberg.org/ebooks/1260", "Charlotte Brontë", 532));
        add(new Book("Detektívka", 14, "Vražda v Orient exprese", "klasická detektívka o vražde v luxusnom vlaku, ktorú rieši slávny Hercule Poirot", 1934, "https://archive.org/download/murderonorientex00chri/murderonorientex00chri.pdf", "Agatha Christie", 256));
        add(new Book("Detektívka", 14, "Štúdia v šarláte", "prvý román o Sherlockovi Holmesovi a jeho metóde deduktívneho usudzovania", 1887, "https://www.gutenberg.org/ebooks/244", "Arthur Conan Doyle", 188));
        add(new Book("Detektívka", 14, "Da Vinciho kód", "thriller o symboloch, tajomstvách a hľadaní Svätého grálu cez umenie a históriu", 2003, "https://books.google.com/books?id=UKuG5KeEePYC", "Dan Brown", 489));
        add(new Book("Detektívka", 14, "Vražda na Nile", "napínavá detektívka o vražde počas plavby po Níle s nečakaným rozuzlením", 1937, "https://archive.org/download/deathonnile00chri/deathonnile00chri.pdf", "Agatha Christie", 288));
        add(new Book("Detektívka", 14, "Dievča s dračím tetovaním", "severský krimi thriller o novinárke a hackerke odhaľujúcej temné rodinné tajomstvá", 2005, "https://books.google.com/books?id=ZFp1QgAACAAJ", "Stieg Larsson", 672));
        add(new Book("Sci-fi", 16, "1984", "dystopický román o totalitnej spoločnosti pod neustálym dohľadom Veľkého brata", 1949, "https://www.gutenberg.org/ebooks/2264", "George Orwell", 328));
        add(new Book("Sci-fi", 16, "Duna", "epická sci-fi sága o politike, náboženstve a ekológii na púštnej planéte Arrakis", 1965, "https://archive.org/download/dune0000herb/dune0000herb.pdf", "Frank Herbert", 896));
        add(new Book("Sci-fi", 16, "Neuromancer", "pioniersky kyberpunk román o hackerovi v kyberpriestore a umelej inteligencii", 1984, "https://archive.org/download/neuromancer00gibs/neuromancer00gibs.pdf", "William Gibson", 271));
        add(new Book("Sci-fi", 16, "451 stupňov Fahrenheita", "dystopický príbeh o spoločnosti, kde sú knihy zakázané a hasiči pália literatúru", 1953, "https://archive.org/download/fahrenheit45100brad/fahrenheit45100brad.pdf", "Ray Bradbury", 158));
        add(new Book("Sci-fi", 16, "Hra Enderova", "sci-fi o géniovi, ktorý je trénovaný vo vesmírnej akadémii na boj proti cudzej rase", 1985, "https://archive.org/download/endersgame00card/endersgame00card.pdf", "Orson Scott Card", 324));
        add(new Book("Klasika", 18, "Zločin a trest", "psychologický román o študentovi, ktorý spácha vraždu a zápasí s výčitkami svedomia", 1866, "https://www.gutenberg.org/ebooks/2554", "Fiodor Michajlovič Dostojevskij", 672));
        add(new Book("Klasika", 18, "Moby Dick", "epický príbeh o kapitánovi Ahabovi a jeho posednutí uloviť bielu veľrybu", 1851, "https://www.gutenberg.org/ebooks/2701", "Herman Melville", 635));
        add(new Book("Klasika", 18, "Vojna a mier", "monumentálny román o ruských šľachtických rodinách počas napoleonských vojen", 1869, "https://www.gutenberg.org/ebooks/2600", "Lev Nikolajevič Tolstoj", 1225));
        add(new Book("Klasika", 18, "Ulises", "modernistický román o jednom dni v Dubline plný stream of consciousness a literárnych odkazov", 1922, "https://archive.org/download/ulysses00joyc/ulysses00joyc.pdf", "James Joyce", 732));
        add(new Book("Klasika", 18, "Márna láska", "príbeh o nenaplnenej láske a spoločenských konvenciách v anglickom vyššom spoločenskom prostredí", 1871, "https://www.gutenberg.org/ebooks/145", "George Eliot", 880));

        //===Manga===

        add(new Manga("Shonen", 12, "One Piece", "dobrodružná manga o pirátovi Luffym, ktorý hľadá legendárny poklad One Piece a sníva stať sa kráľom pirátov", 1997, "https://www.viz.com/shonenjump/chapters/one-piece", "Eiichiro Oda", 106, false));
        add(new Manga("Shonen", 12, "Naruto", "príbeh mladého ninju Naruta, ktorý sníva stať sa najsilnejším ninja vodcom svojej dediny", 1999, "https://www.viz.com/shonenjump/chapters/naruto", "Masashi Kishimoto", 72, false));
        add(new Manga("Shonen", 12, "Dragon Ball", "klasická bojová manga o Gokuovi, ktorý trénuje a bojuje proti stále silnejším nepriateľom", 1984, "https://archive.org/details/dragonballvol10000toriyama", "Akira Toriyama", 42, false));
        add(new Manga("Shonen", 12, "Bleach", "príbeh stredoškoláka Ichiga, ktorý získa schopnosti bojovať proti zlým duchom a chrániť ľudí", 2001, "https://www.viz.com/shonenjump/chapters/bleach", "Tite Kubo", 74, false));
        add(new Manga("Shonen", 12, "My Hero Academia", "v superhrdinskom svete nasledujeme Izukuho, chlapca bez schopností, ktorý chce stať sa hrdinom", 2014, "https://www.viz.com/shonenjump/chapters/my-hero-academia", "Kohei Horikoshi", 40, false));
        add(new Manga("Shonen", 14, "Attack on Titan", "v post-apokalyptickom svete ľudstvo bojuje o prežitie proti obrovským humanoidným tvorom zvaným Titáni", 2009, "https://archive.org/details/attackontitan0000isay", "Hajime Isayama", 34, false));
        add(new Manga("Shonen", 14, "Death Note", "psychologický thriller o študentovi, ktorý objaví zápisník schopný zabíjať ľudí a snaží sa vytvoriť dokonalý svet", 2003, "https://archive.org/details/deathnote0000tsug", "Takeshi Obata", 12, false));
        add(new Manga("Shonen", 14, "Fullmetal Alchemist", "príbeh dvoch bratov alchymistov, ktorí hľadajú kameň mudrcov aby obnovili svoje telá po zlyhanom experimente", 2001, "https://archive.org/details/fullmetalalchemi0000hiro", "Hiromu Arakawa", 27, false));
        add(new Manga("Shonen", 14, "Hunter x Hunter", "Gon sa vydáva na cestu stať sa Hunterom a nájsť svojho otca, ktorý je legendárnym Hunterom", 1998, "https://www.viz.com/shonenjump/chapters/hunter-x-hunter", "Yoshihiro Togashi", 37, false));
        add(new Manga("Shonen", 14, "Demon Slayer", "Tanjiro sa stáva lovecom démonov, aby pomstil svoju rodinu a vyliečil svoju sestru premenenú na démona", 2016, "https://www.viz.com/shonenjump/chapters/demon-slayer-kimetsu-no-yaiba", "Koyoharu Gotouge", 23, false));
        add(new Manga("Seinen", 16, "Berserk", "temná fantasy manga o Guts-ovi, osamelom mečiarovi, ktorý bojuje proti démonom v brutálnom stredovekom svete", 1989, "https://archive.org/details/berserk0000miur", "Kentaro Miura", 41, false));
        add(new Manga("Seinen", 16, "Tokyo Ghoul", "Ken Kaneki sa po transplantácii orgánu stáva polovičným ghúlom a musí sa vyrovnať s novou identitou", 2011, "https://archive.org/details/tokyoghoul0000ishida", "Sui Ishida", 14, false));
        add(new Manga("Seinen", 16, "Monster", "neurochirurg Dr. Tenma loví bývalého pacienta, ktorý sa stal sériovým vrahom, čím sa sám stáva hľadaným", 1994, "https://archive.org/details/monster0000naok", "Naoki Urasawa", 18, false));
        add(new Manga("Seinen", 16, "Vagabond", "historická manga založená na živote slávneho samuraja Musašiho, ktorý hľadá cestu meča a duchovného rastu", 1998, "https://archive.org/details/vagabond0000inou", "Takehiko Inoue", 37, false));
        add(new Manga("Seinen", 16, "20th Century Boys", "skupina priateľov z detstva musí čeliť hrozbe tajomného zloducha, ktorý napĺňa ich detské fantázie", 1999, "https://archive.org/details/20thcenturyboys0000uras", "Naoki Urasawa", 22, false));
        add(new Manga("Shojo", 10, "Sailor Moon", "príbeh Usagi, tínedžerky, ktorá sa transformuje na bojovníčku Sailor Moon a chráni Zem pred zlom", 1991, "https://archive.org/details/sailormoon0000take", "Naoko Takeuchi", 18, false));
        add(new Manga("Shojo", 10, "Fruits Basket", "Tohru Hondaová objaví tajomstvo rodiny Soma, že sa menia na zvieratá čínskeho zverokruhu, keď ich objíme", 1998, "https://archive.org/details/fruitsbasket0000taka", "Natsuki Takaya", 23, false));
        add(new Manga("Shojo", 10, "Cardcaptor Sakura", "Sakura objaví magickú knihu a musí zachytiť rozprchnuté karty, aby zachránila svet pred chaosom", 1996, "https://archive.org/details/cardcaptorsakura0000clow", "CLAMP", 12, false));
        add(new Manga("Shojo", 10, "Nana", "príbeh dvoch mladých žien s rovnakým menom, ktoré sa stretnú v Tokiu a prežívajú lásku, priateľstvo a hudbu", 2000, "https://archive.org/details/nana0000yaza", "Ai Yazawa", 21, false));
        add(new Manga("Shojo", 10, "Ouran High School Host Club", "Haruci sa zamýli za chlapca a musí pracovať v host klube plnom bohatých a pohľadných študentov", 2002, "https://archive.org/details/ouranhighschoolh0000hatt", "Bisco Hatori", 18, false));
        add(new Manga("Josei", 18, "Nodame Cantabile", "príbeh dvoch hudobníkov - talentovaného dirigenta Chiakia a excentrickej pianistky Nodame na konzervatóriu", 2001, "https://archive.org/details/nodamecantabile0000nina", "Tomoko Ninomiya", 25, false));
        add(new Manga("Josei", 18, "Chihayafuru", "Chihaya sa venuje tradičnej japonskej karetné hre karuta a snaží sa stať sa najlepšou hráčkou v Japonsku", 2007, "https://archive.org/details/chihayafuru0000suet", "Yuki Suetsugu", 49, false));
        add(new Manga("Josei", 18, "Princess Jellyfish", "Tsukimi žije v dome plnom fujoshi, kým nespozná elegantnú Kuranosuke, ktorá má tajomstvo", 2008, "https://archive.org/details/princessjellyfish0000higu", "Akiko Higashimura", 17, false));
        add(new Manga("Josei", 18, "Honey and Clover", "príbeh umeleckých študentov, ktorí prežívajú prvú lásku, priateľstvo a hľadanie zmyslu života", 2000, "https://archive.org/details/honeyclover0000uimi", "Chica Umino", 10, false));
        add(new Manga("Josei", 18, "Paradise Kiss", "Yukari sa zapletie so skupinou módnych študentov a objaví svoju vášeň pre modelingu a lásku", 1999, "https://archive.org/details/paradisekiss0000yaza", "Ai Yazawa", 5, false));
        add(new Manga("Sports", 12, "Slam Dunk", "Hanamichi Sakuragi sa stáva basketbalovým hráčom, aby zapáčil sa dievčaťu, ale objaví vášeň pre šport", 1990, "https://archive.org/details/slamdunk0000inou", "Takehiko Inoue", 31, false));
        add(new Manga("Sports", 12, "Haikyuu!!", "Hinata, malý hráč volejbalu, sa snaží stať sa najlepším napriek svojej výške a tvorí rivalitu s Kageyamou", 2012, "https://archive.org/details/haikyu0000furu", "Haruichi Furudate", 45, false));
        add(new Manga("Sports", 12, "Captain Tsubasa", "Tsubasa Ozora je talentovaný futbalista, ktorý sníva stať sa majstrom sveta a vedie svoj tím k víťazstvám", 1981, "https://archive.org/details/captaintsubasa0000taka", "Yoichi Takahashi", 37, false));
        add(new Manga("Sports", 12, "Kuroko's Basketball", "Kuroko, takmer neviditeľný hráč, spojí sily s talentovaným Kagamim, aby porazili bývalých spoluhráčov", 2008, "https://archive.org/details/kurokosbasketbal0000fuji", "Tadatoshi Fujimaki", 30, false));
        add(new Manga("Sports", 12, "Hajime no Ippo", "Ippo Makunouchi objaví talent pre box a stúpa v rebríčkoch, aby sa stal šampiónom v ťažkej váhe", 1989, "https://archive.org/details/hajimenoippo0000mori", "George Morikawa", 137, false));

        //===Encyclopedia====

        add(new Encyclopedia("Astronómia", 12, "Encyklopédia astronómie", "komplexná príručka o vesmíre, hviezdach, planétach a kozmickom priestore s detailnými ilustráciami", 2002, "https://archive.org/details/philipsastronomy00moor", "Patrick Moore", "Vedecká"));
        add(new Encyclopedia("Biologia", 10, "Encyklopédia biológie", "obsiahla encyklopédia o živých organizmoch, ekosystémoch, bunkovej biológii a evolúcii", 1996, "https://archive.org/details/encyclopedia-of-biology", "Don Rittner", "Prírodovedná"));
        add(new Encyclopedia("Chémia", 14, "Malá encyklopédia chémie", "slovenská encyklopédia s vyše 3500 heslami o chemických prvkoch, zlúčeninách a procesoch", 1981, "https://archive.org/details/mala-encyklopedia-chemie", "Jaroslav Bína", "Chemická"));
        add(new Encyclopedia("História", 12, "Encyklopédia svetových dejín", "kompletná encyklopédia pokrývajúca dejiny ľudstva od praveku po súčasnosť", 2011, "https://archive.org/details/encyclopediaofworldhistory_201912", "Alfred J. Andrea", "Historická"));
        add(new Encyclopedia("Medicína", 16, "De Medicina", "klasická rímska medicínska encyklopédia o diéte, farmakológii a chirurgii z 1. storočia", 47, "https://archive.org/details/de-medicina-celsus", "Aulus Cornelius Celsus", "Medicínska"));
        add(new Encyclopedia("Fyzika", 14, "Encyklopédia fyziky", "komplexný prehľad fyzikálnych zákonov, teórií a experimentov pre študentov a odborníkov", 1996, "https://archive.org/details/encyclopediaofph00ravi", "Robert M. Besançon", "Fyzikálna"));
        add(new Encyclopedia("Zoológia", 10, "Encyklopédia zvierat", "ilustrovaná príručka o živočíšnej ríši s fotografiami a informáciami o tisíckach druhov", 2012, "https://archive.org/details/animalsvisualencyclopedia", "DK Publishing", "Biologická"));
        add(new Encyclopedia("Geografia", 12, "Encyklopédia zemepisu", "komplexný prehľad o kontinentoch, krajinách, mestách a prírodných zdrojoch sveta", 2005, "https://archive.org/details/worldgeographyen0000unse", "Peter Haggett", "Geografická"));
        add(new Encyclopedia("Technika", 14, "Encyklopédia techniky", "prehľad technologických vynálezov, strojov a priemyselných procesov od praveku po súčasnosť", 2000, "https://archive.org/details/encyclopediaofte00mccu", "Donald Clarke", "Technická"));
        add(new Encyclopedia("Umenie", 16, "Encyklopédia svetového umenia", "monumentálne dielo pokrývajúce dejiny výtvarného umenia, architektúry a sochárstva", 1996, "https://archive.org/details/encyclopediaofar00myin", "Bernard S. Myers", "Umelecká"));
        add(new Encyclopedia("Filozofia", 16, "Encyklopédia filozofie", "komplexný prehľad filozofických smerov, mysliteľov a konceptov od antiky po súčasnosť", 2006, "https://archive.org/details/encyclopediaofph00donc", "Donald M. Borchert", "Filozofická"));
        add(new Encyclopedia("Psychológia", 14, "Encyklopédia psychológie", "obsiahla príručka o psychologických teóriách, metódach a aplikáciách v praxi", 2000, "https://archive.org/details/encyclopediaofps00eysen", "Hans J. Eysenck", "Psychologická"));
        add(new Encyclopedia("Matematika", 12, "Encyklopédia matematiky", "komplexný prehľad matematických disciplín, teórií a ich aplikácií vo vede a technike", 1988, "https://archive.org/details/encyclopediaofma00grat", "Grattan-Guinness", "Matematická"));
        add(new Encyclopedia("Literatúra", 14, "Encyklopédia svetovej literatúry", "prehľad literárnych diel, autorov a smerov od antiky po súčasnú literatúru", 1997, "https://archive.org/details/encyclopediaofwo00laza", "Steven R. Serafin", "Literárna"));
        add(new Encyclopedia("Hudba", 12, "Encyklopédia hudby", "komplexný prehľad hudobných žánrov, skladateľov, interpretov a hudobnej teórie", 2003, "https://archive.org/details/oxfordcompaniont00hoer", "Alison Latham", "Hudobná"));
        add(new Encyclopedia("Náboženstvo", 16, "Encyklopédia náboženstiev", "obsiahly prehľad svetových náboženstiev, ich histórie, náuky a kultúrneho vplyvu", 2005, "https://archive.org/details/encyclopediaofre00jone", "Lindsay Jones", "Náboženská"));
        add(new Encyclopedia("Právo", 18, "Encyklopédia práva", "komplexná príručka o právnych systémoch, legislatíve a právnej histórii", 2009, "https://archive.org/details/encyclopediaofam00schul", "David A. Schultz", "Právna"));
        add(new Encyclopedia("Ekonomika", 16, "Encyklopédia ekonomiky", "prehľad ekonomických teórií, systémov a finančných trhov pre študentov a odborníkov", 2008, "https://archive.org/details/encyclopediaofec00durl", "Steven N. Durlauf", "Ekonomická"));
        add(new Encyclopedia("Architektúra", 14, "Encyklopédia architektúry", "ilustrovaná príručka o stavebných štýloch, staviteľoch a ikonických budovách sveta", 2008, "https://archive.org/details/encyclopediaofar00cuit", "Cyril M. Harris", "Architektonická"));
        add(new Encyclopedia("Film", 14, "Encyklopédia filmu", "komplexný prehľad kinematografie, režisérov, hercov a filmových smerov", 2007, "https://archive.org/details/encyclopediaoffi00nash", "Nash", "Filmová"));
        add(new Encyclopedia("Šport", 10, "Encyklopédia športu", "obsiahla príručka o športových disciplínach, pravidlách, histórii a významných športovcoch", 2003, "https://archive.org/details/encyclopediaofsp00cox", "Michael Cox", "Športová"));
        add(new Encyclopedia("Astronómia", 8, "Detská encyklopédia vesmíru", "farebná encyklopédia pre deti o vesmíre, planétach a kozmických objavoch s ilustráciami", 2010, "https://archive.org/details/childrensencyclo0000unse", "DK Publishing", "Detská vedecká"));
        add(new Encyclopedia("Príroda", 8, "Encyklopédia prírody", "ilustrovaná príručka pre deti o rastlinách, zvieratách a prírodných javoch", 2005, "https://archive.org/details/natureencycloped0000unse", "DK Publishing", "Detská prírodovedná"));
        add(new Encyclopedia("Dinosaurus", 8, "Encyklopédia dinosaurov", "farebná encyklopédia pre mladých čitateľov o dinosauroch a pravekom svete", 2014, "https://archive.org/details/dinosaursencyclo0000unse", "DK Publishing", "Detská paleontologická"));
        add(new Encyclopedia("Veda", 12, "Encyklopédia vedy", "komplexný prehľad vedeckých disciplín, objavov a technologických inovácií", 2006, "https://archive.org/details/encyclopediaofsc00mchu", "Katherine McMahon", "Vedecká"));
        add(new Encyclopedia("Vojenstvo", 16, "Encyklopédia vojenských dejín", "prehľad vojenských konfliktov, stratégií, zbraní a významných bitiek v histórii", 2001, "https://archive.org/details/oxfordcompaniont00hola", "Richard Holmes", "Vojenská"));
        add(new Encyclopedia("Mýtológia", 12, "Encyklopédia mytológie", "prehľad svetových mytológií, bohov, hrdinov a mytologických príbehov", 2004, "https://archive.org/details/encyclopediaofmy00cote", "Arthur Cotterell", "Humanitná"));
        add(new Encyclopedia("Jazykoveda", 14, "Encyklopédia jazykov", "prehľad svetových jazykov, ich histórie, gramatických štruktúr a lingvistiky", 2006, "https://archive.org/details/encyclopediaofla00ryde", "R.E. Asher", "Jazykovedná"));
        add(new Encyclopedia("Kuchárska", 10, "Encyklopédia gastronómie", "obsiahla príručka o svetovej kuchyni, ingredienciách a kulinárskych technikách", 2009, "https://archive.org/details/encyclopediaofga0000unse", "Prosper Montagné", "Gastronomická"));
        add(new Encyclopedia("Zdravie", 14, "Encyklopédia zdravia", "komplexný prehľad o ľudskom tele, chorobách, prevencii a zdravom životnom štýle", 2005, "https://archive.org/details/encyclopediaofhe0000unse", "British Medical Association", "Zdravotnícka"));
    }
}